### ISSUE TITLE
Alternative download source

### ISSUE THREAD

**Issue by IzzySoft** [thibseisel/android-odeon#5]
Thanks a lot for making your nice, light-weight and tracker-free app available as open source! Would you also consider making the APK available outside of Play Store – for those who cannot use it or rather avoid it for e.g. privacy reasons? Possibilities would e.g. be [tagging your releases](https://github.com/thibseisel/android-odeon/releases) and attaching it there – or tagging and having your app built and included with [F-Droid](https://f-droid.org/).

**Comment by thibseisel** [comment]
Of course I can !
I thought that Google Play was the de-facto application store for Android, that's why I haven't considered publishing to alternative stores.

Note that since `Odeon` uses Android `MediaSession`, it might have weak connections with other Google stuff, such as Google Assistant and Android Auto.
If that's not a problem, I'd be glad to post APKs on F-Droid for the latest release and the following ones !

**Comment by IzzySoft** [comment]
If it uses proprietary libraries for those "weak connections" (a quick glance at the app's `build.gradle` didn't reveal any to me), F-Droid itself will not accept it (by the way: F-Droid always builds from the source, you cannot simply upload an APK there – it's all "pure FOSS").

But if you'd attach the APKs to your releases (starting with the latest one is fully sufficient), I can pick them for [my F-Droid repo](https://apt.izzysoft.de/fdroid), which in a way is considered to the official F-Droid repo what "nonfree" is for Debian – and also served as "stepping stone" for many apps in the past (until they could match the rather strong [inclusion citeria](https://f-droid.org/wiki/page/Inclusion_Policy) of F-Droid – those for my repo [are more relax](https://gitlab.com/IzzyOnDroid/repo)). Updates would be fetched there automatically within 24h of your attaching the APK to a new tag.

With your app there, we could also see what my library scanner reports. If it doesn't come up with some so-called `NonFreeDep`, I gladly help you [filing an RFP](https://gitlab.com/fdroid/rfp/issues) (Request For Packaging) to move it over to the official repo – wouldn't be the first app going that way (actually, not even one of the first hundred apps). I'd suggest starting this way – if that's OK with you.

And yes, Google considers Play Store the de-facto application store for Android (and the only one at that). But what would you expect from them? They've got an empire to keep-together 😆 There are several more [alternative markets](https://android.stackexchange.com/tags/alternative-markets/info) which are more or less known. F-Droid is the only "bigger" one with focus on FOSS and privacy – the latter going as far as possible, with no permanent logging, no (user) accounts etc.

**Comment by IzzySoft** [comment]
Any news on this? Could you attach the APK to releases (starting with the latest one – no need to "walk back to Adam and Eve")?

**Comment by thibseisel** [comment]
Hi @IzzySoft,
Following the recent release of the stable version 2.0.1, I attached the resulting APK in the release page, tag 2.0.1. I also submitted the app to F-Droid : https://gitlab.com/fdroid/rfp/issues/1186

**Comment by IzzySoft** [comment]
@thibseisel great! Yes, I just saw the RFP popping up. As you also attached the APK, I took the freedom to [add your app to my repo](https://apt.izzysoft.de/fdroid/index/apk/fr.nihilus.music) already, which acts as "staging" for F-Droid in some cases (and as "non-free" in some others) – should show up there in a few minutes hopefully. Scan there looks good; as soon as the main repo's bot performed its scan, I'll copy the metadata over.

Thanks!

Besides: would you consider adding [Fastlane file structure](https://gitlab.com/snippets/1895688) to your repo, so F-Droid can pick up screenshots etc (and you can maintain the app description yourself)?

**Comment by mondlicht-und-sterne** [comment]
hi there, @IzzySoft and @thibseisel . 
i promote on mastodon under the hashtag [#mastoart](https://mastodon.technology/web/statuses/103844577171779517) and on my [pixelfed](https://pixelfed.social/p/mondstern/145901814624161792) account under open source software and projects and had recently painted your **Odeon Music Player** as acrylic picture to promote it.
when the corona crisis is over, exhibitions are also planned. in berlin (germany) there will be the first one.

**Comment by IzzySoft** [comment]
Thanks @mondlicht-und-sterne! :heart_eyes:

@thibseisel his MastoArt is famous already, you can be proud!

**Comment by mondlicht-und-sterne** [comment]
[Odeon](https://cloud.moooon.de/index.php/s/bZtfXZYR44PaHmP)

Here you can see, on the left wall, the promotion for your Odeon player.
Thank you for the Odeon Player.
Its to see in my first exhibition in Berlin / Germany since end of august this year.

**Comment by IzzySoft** [comment]
Thanks again for your help and the nice app, @thibseisel! Now that it's available at F-Droid, I'll remove it from my repo again. Should you want it back with me for some reason, just say and I e-establish it.

And as this issue is now solved, I'll close it :smiley:
