### ISSUE TITLE
Build for version 2.0.2?

### ISSUE THREAD

**Issue by danhansen** [thibseisel/android-odeon#8]
I just tried your music player out for the first time today, and I was really impressed! The interface is very functional, but also clean and simple (no fluff).

I'm currently running Android 10 and noticed that artwork wasn't being displayed. I also noticed that version 2.0.2 appears to have a fix for this issue. Is there a reason you haven't published a build for version 2.0.2 yet?

Thanks,
Dan

**Comment by thibseisel** [comment]
Hi Dan,

Many thanks for your positive feedback, I'm glad someone else appreciate my minimalistic music player!
The 2.0.2 release is now available for download on the release tab on Github. Enjoy Odeon with its album artworks back!

In order for you to stay up-to-date, I still have some work to do to automatically publish the APK on Github and FDroid. Stay tuned!

Thibault
